[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EnProg"
authors = [{name = "Locutusque", email = "locutusque.airshipcraft@gmail.com"}]
dynamic = ["version", "description"]
